services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_CONFIG=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-cmmc_db}
      - DB_USER=${DB_USER:-cmmc_user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      # Database connection pool settings
      - DB_POOL_MIN_CONN=${DB_POOL_MIN_CONN:-5}
      - DB_POOL_MAX_CONN=${DB_POOL_MAX_CONN:-25}
      - DB_POOL_IDLE_TIMEOUT=${DB_POOL_IDLE_TIMEOUT:-60}
      - SECRET_KEY=${SECRET_KEY:-default_dev_key_change_in_production}
      # Email configuration
      - MAIL_SERVER=${MAIL_SERVER:-sandbox.smtp.mailtrap.io}
      - MAIL_PORT=${MAIL_PORT:-2525}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-true}
      - MAIL_USERNAME=${MAIL_USERNAME:-bc366ad3b451bc}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-8d801eecf49e5a}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER:-cmmc-tracker@example.com}
      # Redis configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app/cmmc_tracker
      # Control Seeding Behavior (set to true to run seed_db.py on startup)
      - RUN_FULL_SEED=${RUN_FULL_SEED:-true}
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-cmmc_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-cmmc_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data:
